-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Tiempo de generación: 12-03-2020 a las 01:45:02
-- Versión del servidor: 10.1.35-MariaDB
-- Versión de PHP: 7.2.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `themoviesdb`
--
CREATE DATABASE IF NOT EXISTS `themoviesdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `themoviesdb`;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `movies`
--

DROP TABLE IF EXISTS `movies`;
CREATE TABLE `movies` (
  `id` int(11) UNSIGNED NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `overview` mediumtext,
  `vote_average` decimal(3,1) DEFAULT NULL,
  `release_date` datetime DEFAULT NULL,
  `original_language` varchar(11) DEFAULT NULL,
  `poster` varchar(255) DEFAULT NULL,
  `createdAt` timestamp NULL DEFAULT NULL,
  `updatedAt` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `movies`
--

INSERT INTO `movies` (`id`, `title`, `overview`, `vote_average`, `release_date`, `original_language`, `poster`, `createdAt`, `updatedAt`) VALUES
(1, 'Sonic the Hedgehog', 'Sonic, el famoso erizo azul de SEGA vivirá su primera aventura en la pantalla grande. En esta adaptación cinematográfica basada en la conocida saga de videojuegos podremos ver a los personajes icónicos de la franquicia. Su protagonista será Sonic, el erizo con la habilidad de correr a la velocidad del sonido y que, junto con sus amigos el zorro Tails y el equidna Knuckles, combaten con el malvado Doctor Eggman, que siempre está tratando de dominar el mundo y apoderarse de las esmeraldas del caos.', '7.2', '2020-02-12 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/A7hhUj9Fq6E6FhGsENJTCmnCmt4.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(2, 'A Rainy Day in New York', 'Dos jóvenes llegan a Nueva York durante un fin de semana donde se topan con el mal tiempo y una serie de aventuras.', '6.7', '2019-07-26 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/ya9ojfuWylP4P6iiaIaxz67Chu0.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(3, 'Ad Astra', 'El futuro cercano, un tiempo en el que tanto la esperanza como la adversidad impulsan a la humanidad a mirar hacia las estrellas y más allá. Mientras un misterioso fenómeno amenaza con destruir la vida en el planeta Tierra, el astronauta Roy McBride emprende una misión a través de la inmensidad del espacio y sus muchos peligros para descubrir la verdad sobre una expedición perdida que décadas antes afrontó audazmente el vacío y el silencio en busca de lo desconocido.', '6.0', '2019-09-17 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/kK6Oq4JywUNXmJ299efUkv1h6Mn.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(4, 'Avengers: Endgame', 'Después de los eventos devastadores de \'Vengadores: Infinity War\', el universo está en ruinas debido a las acciones de Thanos. Con la ayuda de los aliados que quedaron, los Vengadores deberán reunirse una vez más para intentar deshacer sus acciones y restaurar el orden en el universo de una vez por todas, sin importar cuáles sean las consecuencias... Cuarta y última entrega de la saga \"Vengadores\".', '8.3', '2019-04-24 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/br6krBFpaYmCSglLBWRuhui7tPc.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(5, 'Big Hero 6', 'En la metrópolis de San Fransokyo (cruce de San Francisco y Tokio), vive Hiro Hamada, quien aprende a sacar provecho de su capacidad gracias a su brillante hermano Tadashi y sus también brillantes amigos: la buscadora de adrenalina GoGo Tamago, el meticuloso de la limpieza Wasabi-No-Ginger, la genia de la química Honey Lemon y el fanático de los cómics Fred. Cuando tras un devastador giro de los acontecimientos, se ven envueltos en una peligrosa conspiración que tiene lugar en las calles de San Fransokyo, Hiro recurre a su amigo más íntimo: un robot llamado Baymax, y transforma al grupo en una banda de héroes de última tecnología decididos a resolver el misterio. Adaptación animada del cómic de Marvel.', '7.8', '2014-10-24 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/dttSIaRB0D06AVL2Mz7ilnxdI8q.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(6, 'Jumanji: The Next Level', 'En esta ocasión, los \'jugadores\' vuelven al juego, pero sus personajes se han intercambiado entre sí, lo que ofrece un curioso plantel: los mismos héroes con distinta apariencia. Pero, ¿dónde está el resto de la gente? Los participantes sólo tienen una opción: jugar una vez más a esta peligrosa partida para descubrir qué es realmente lo que está sucediendo.', '6.8', '2019-12-04 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/b1bTpxh0lRfw7kwRrWPeMOo7jbY.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(7, 'El Camino: A Breaking Bad Movie', 'Tiempo después de los eventos sucedidos tras el último episodio de la serie Breaking Bad, el fugitivo Jesse Pinkman huye de sus perseguidores, de la ley y de su pasado.', '6.9', '2019-10-11 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/bykSMP21J3RzX3YmYo6hlVH4UE6.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(8, 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)', 'Después de separarse de Joker, Harley Quinn y otras tres heroínas (Canario Negro, Cazadora y Renée Montoya) unen sus fuerzas para salvar a una niña (Cassandra Cain) del malvado rey del crimen Máscara Negra.', '6.8', '2020-02-05 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/4GCqF17I2ST5M8iSkwh1jwqvi7F.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(9, 'Mission: Impossible - Fallout', 'Sexta entrega de la saga. En esta ocasión presenta a Ethan Hunt (Tom Cruise) y su equipo IMF (Alec Baldwin, Simon Pegg, Ving Rhames), con algunos aliados conocidos (Rebecca Ferguson, Michelle Monaghan), en una lucha contrarreloj después de que una misión salga mal.', '7.3', '2018-07-13 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/cUlWqDLEYMN3OWlOZ0U18WcIw5F.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(10, 'Star Wars: The Last Jedi', 'La fuerza siente un cambio y los Maestros Jedi saben que es el momento de regresar. La galaxia se encuentra perdida y separada, y deberán unir fuerzas si no quieren que sea el fin de la paz. Con el rumor de una guerra, los pocos aliados que quedan emprenderán la búsqueda para aumentar sus aliados, mientras se enfrentan a la desconfianza y el temor de aquellos que no olvidan ni perdonan. Mundos casi olvidados, personajes misteriosos y viejas caras conocidas, una nueva aventura está a punto de comenzar para mantener la frágil supervivencia de La República, mientras se preparan para lo que está por llegar.', '7.0', '2017-12-13 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/rjBwhsOzHKUw2NIOrE7aMqjfe6s.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(11, 'Spenser Confidential', 'Spenser, un expatrullero de Boston que acaba de salir de prisión, y Hawk, un aspirante a luchador, se alian para descubrir la verdad detrás de la muerte de dos agentes de policía.', '6.7', '2020-03-06 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/8C2AQNvg63t1Z8nWfZwAMYMa5ZS.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(12, 'Bloodshot', 'Ray Garrison (Vin Diesel), también conocido como Bloodshot, es resucitado por la compañía Rising Spirit Technologies a través del uso de nanotecnología. Mientras lucha por recuperar la memoria, Ray trata de volver al ser el que era antes de sufrir el accidente que dejaría amnésico. Película basada en el cómic \"Valiant\", creado por Kevin VanHook, Don Perlin y Bob Layton.', '5.8', '2020-02-20 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/nUb7lOVlPbHPNib3CwAYjeqjUF7.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(13, '1917', 'Nos encontramos en el año 1917. La Guerra Mundial amenazaba con cambiar, para siempre, el orden mundial. Ante la amenaza que se cernía, Estados Unidos decidió entrar en el conflicto con el objetivo de desequilibrar la balanza que caracterizaba a la contienda.', '8.0', '2019-12-25 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/AuGiPiGMYMkSosOJ3BQjDEAiwtO.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(14, '13 Hours: The Secret Soldiers of Benghazi', 'El 11 de septiembre de 2012, en el aniversario de los ataques terroristas a las Torres Gemelas y al Pentágono, un grupo de milicianos islamistas atentaron contra el consulado estadounidense y un anexo cercano de la CIA en Bengasi, Libia. Un equipo de seis miembros de Operaciones Especiales de Estados Unidos fue enviado para rescatar a los supervivientes.', '7.1', '2016-01-13 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/6JgLlqmVcbz139YRSTcuHn80xwn.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(15, '기생충', 'Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una interrelación de resultados imprevisibles.', '8.6', '2019-05-30 00:00:00', 'ko', 'https://image.tmdb.org/t/p/w500/4N55tgxDW0RRATyrZHbx0q9HUKv.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(16, 'Guardians of the Galaxy', 'El temerario aventurero Peter Quill es objeto de un implacable cazarrecompensas después de robar una misteriosa esfera codiciada por Ronan, un poderoso villano cuya ambición amenaza todo el universo. Para poder escapar del incansable Ronan, Quill se ve obligado a pactar una complicada tregua con un cuarteto de disparatados inadaptados: Rocket, un mapache armado con un rifle, Groot, un humanoide con forma de árbol, la letal y enigmática Gamora y el vengativo Drax the Destroyer. Pero cuando Quill descubre el verdadero poder de la esfera, deberá hacer todo lo posible para derrotar a sus extravagantes rivales en un intento desesperado de salvar el destino de la galaxia.', '7.9', '2014-07-30 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/9Ju7p4daJi5rcTUghYZxHlP15ia.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(17, 'The Invisible Man', 'Después de que su abusivo ex novio se suicide, la ingenua viuda Cecilia comienza a reconstruir su vida para mejor. Sin embargo, su sentido de la realidad se pone en tela de juicio cuando comienza a sospechar que su ex novio en realidad no está muerto, como había pensado.', '7.2', '2020-02-26 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/tRGIqrs4Z2aIZPVRcapvgGnTLnI.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(18, 'Captain Marvel', 'La historia sigue a Carol Danvers mientras se convierte en uno de los héroes más poderosos del universo, cuando la Tierra se encuentra atrapada en medio de una guerra galáctica entre dos razas alienígenas. Situada en los años 90, \'Capitana Marvel\' es una historia nueva de un período de tiempo nunca antes visto en la historia del Universo Cinematográfico de Marvel.', '7.0', '2019-03-06 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/d3p5JuwN7dG0TvrN5h4ZY4tMOEX.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(19, 'Milea: Suara dari Dilan', '', '6.7', '2020-02-13 00:00:00', 'id', 'https://image.tmdb.org/t/p/w500/o1D5kEPPOGReel6CipiKOY5tPJt.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(20, 'The Dark Knight', 'Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.', '8.4', '2008-07-16 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/8QDQExnfNFOtabLDKqfDQuHDsIg.jpg', '2020-03-11 19:53:16', '2020-03-11 19:53:16'),
(21, 'Frozen II', '¿Por qué nació Elsa con poderes mágicos? La respuesta le está llamando y amenaza su reino. Junto con Anna, Kristoff, Olaf y Sven emprenderá un viaje peligroso e inolvidable. En \'Frozen: El Reino del Hielo\', Elsa temía que sus poderes fueran demasiado para el mundo. En \'Frozen 2\', deseará que sean suficientes.', '7.1', '2019-11-20 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/jnFCk7qGGWop2DgfnJXeKLZFuBq.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(22, 'Knives Out', 'Cuando el renombrado novelista de misterio Harlan Thrombey es encontrado muerto en su mansión justo después de su 85 cumpleaños, el inquisitivo y cortés detective Benoit Blanc es misteriosamente reclutado para investigar. Se moverá entre una red de pistas falsas y mentiras interesadas para tratar de descubrir la verdad tras la prematura muerte del escritor.', '7.8', '2019-11-27 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/wdjjISkTL7euUD8mogXTqipgFpz.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(23, 'Captain America: Civil War', '\"Captain America: Civil War” continúa la historia de “Avengers: Age of Ultron”, con Steve Rogers liderando un nuevo equipo de Vengadores en su esfuerzo por proteger a la humanidad. Tras otro incidente internacional relacionado con los Vengadores que ocasiona daños colaterales, la presión política fuerza a crear un sistema de registro y un cuerpo gubernamental para determinar cuándo se requiere los servicios del equipo. El nuevo status quo divide a los Vengadores mientras intentan salvar al mundo de un nuevo y perverso villano.\"', '7.4', '2016-04-27 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/j3DXwoJwbFTqgBOfIWct8H3LYpr.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(24, 'Ford v Ferrari', 'Se centra en un excéntrico y decidido equipo americano de ingenieros y diseñadores liderados por el visionario automovilístico Carroll Shelby (Damon) y su conductor británico Ken Miles (Bale). Henry Ford II y Lee Iacocca les dan la misión de construir desde cero un nuevo automóvil con el fin de derrocar el dominio de Ferrari en el Campeonato del Mundo de Le Mans de 1966.', '7.8', '2019-11-13 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/kFkZFPBU7vnDDu4m9eOgk7w9W7O.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(25, 'Joker', 'Arthur Fleck es un hombre ignorado por la sociedad, cuya motivación en la vida es hacer reír. Pero una serie de trágicos acontecimientos le llevarán a ver el mundo de otra forma. Película basada en Joker, el popular personaje de DC Comics y archivillano de Batman, pero que en este film toma un cariz más realista y oscuro.', '8.2', '2019-10-02 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/v0eQLbzT6sWelfApuYsEkYpzufl.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(26, 'Star Wars', 'La princesa Leia, líder del movimiento rebelde que desea reinstaurar la República en la galaxia en los tiempos ominosos del Imperio, es capturada por las malévolas Fuerzas Imperiales, capitaneadas por el implacable Darth Vader, el sirviente más fiel del emperador. El intrépido Luke Skywalker, ayudado por Han Solo, capitán de la nave espacial \"El Halcón Milenario\", y los androides, R2D2 y C3PO, serán los encargados de luchar contra el enemigo y rescatar a la princesa para volver a instaurar la justicia en el seno de la Galaxia.', '8.2', '1977-05-25 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/4hOUzmButYUeON0prG3RpbqS7ag.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(27, 'Batman Begins', '¿Cómo cambia un hombre el mundo? Es una pregunta que obsesiona a Bruce Wayne al igual que el fantasma de sus padres, muertos a tiros ante sus ojos en las calles de Gotham una noche que cambió su vida para siempre. Atormentado por la culpa y la ira, el desilusionado heredero industrial desaparece de Gotham y viaja en secreto por el mundo, buscando los medios de luchar contra la injusticia y utilizar el miedo contra los que se aprovechan de los que tienen miedo. Con la ayuda de su leal mayordomo Alfred, el detective Jim Gordon - uno de los pocos buenos policías de las fuerzas del orden público de Gotham - y Lucius Fox, su aliado en la división de Ciencias Aplicadas de Wayne Enterprises, Bruce Wayne libera a su imponente alter ego: Batman, un justiciero enmascarado que utiliza la fuerza, la inteligencia y un despliegue de artefactos de alta tecnología para combatir las fuerzas siniestras que amenazan con destruir la ciudad.', '7.6', '2005-06-10 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/6yMWU1vWkOBbNRIwOxhetd2aHhO.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(28, '仮面ライダージオウNEXT TIME：ゲイツ、マジェスティ', '', '0.0', '2020-04-22 00:00:00', 'ja', 'https://image.tmdb.org/t/p/w500/46UQgss4eeiLt1XE2GpHpPkzjIi.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(29, 'Ant-Man', 'Armado con la asombrosa capacidad de reducir su tamaño a la dimensiones de un insecto, el estafador Scott Lang (Paul Rudd) debe sacar a relucir al héroe que lleva dentro y ayudar a su mentor, el doctor Hank Pym (Michael Douglas), a proteger de una nueva generación de amenazas el secreto que se esconde tras el traje de Ant-Man, con un casco que le permite comunicarse con las hormigas. A pesar de los obstáculos aparentemente insuperables que les acechan, Pym y Lang deben planear y llevar a cabo un atraco para intentar salvar al mundo.', '7.1', '2015-07-14 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/f6D5e1NUNVMujKWhOTrzkOj9l7W.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(30, 'Dragonheart: Vengeance', 'Lukas, un joven agricultor cuya familia es asesinada por salvajes guerreros, se embarca en una aventura épica en busca de venganza, formando un trío imposible con un dragón majestuoso y un mercenario espadachín llamado Darius.', '5.7', '2020-02-04 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/qZ1KAgfdeNbzrNYKW4BIRHdEBJ9.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(31, 'Onward', 'Ambientado en un mundo de fantasía suburbana, dos hermanos elfos adolescentes, Ian y Barley Lightfood, se embarcan en una aventura en la que se proponen descubrir si existe aún algo de magia en el mundo que les permita pasar un último día con su padre, que falleció cuando ellos eran aún muy pequeños como para poder recordarlo.', '8.0', '2020-02-29 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/tHWeWBBOlkPYdlZcjSKeToQvgZg.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(32, 'Contagion', 'De repente, sin saber cuál es su origen, aunque todo hace sospechar que comienza con el viaje de una norteamericana a un casino de Hong Kong, un virus mortal comienza a propagarse por todo el mundo. En pocos días, la enfermedad empieza a diezmar a la población. El contagio se produce por mero contacto entre los seres humanos. Un thriller realista y sin efectos especiales sobre los efectos de una epidemia.', '6.4', '2011-09-08 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/rKUPugXr3n8sGRoBbXByLm83rK6.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(33, 'ガールズ＆パンツァー 最終章 第2話', '', '5.2', '2019-06-15 00:00:00', 'ja', 'https://image.tmdb.org/t/p/w500/2UPHyMm8fE22yvTFVGu1LW2nVF0.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(34, 'Spies in Disguise', 'Puede decirse que el superespía Lance Sterling y el científico Walter Beckett no tienen nada que ver entre sí: Lance es relajado, educado y caballeroso. Walter lo opuesto. Lo que le falta a Walter de habilidades sociales lo compensa con una dosis extra de ingenio e inventiva, con los que crea fascinantes artilugios que Lance usa en sus épicas misiones. Pero cuando los acontecimientos sorprenden con un giro inesperado, Walter y Lance tendrán que confiar el uno en el otro… Y todo el mundo estará en peligro.', '7.3', '2019-12-24 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/kKBHCrorQRfFMksOXLq38yyDIJK.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(35, 'Little Women', 'Amy, Jo, Beth y Meg son cuatro hermanas adolescentes que se embarcan en unas vacaciones con su madre, pero sin su padre, un evangelista itinerante. A medida que atraviesan el estado de Massachusetts, sumido en plena Guerra Civil, descubren el amor y la importancia de los lazos familiares.', '8.0', '2019-12-25 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/z2wBWFEQ9FE0RcjmWXz3vvSNPfT.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(36, 'Terminator: Dark Fate', 'Sarah Connor une todas sus fuerzas con una mujer cyborg para proteger a una joven de un extremadamente poderoso y nuevo Terminator.', '6.3', '2019-10-23 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/k7PuHoj2oE7nEHExwliF2FSXFnr.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(37, 'Zombieland: Double Tap', 'En esta secuela y empleando el característico sentido del humor del que hizo gala \"Zombieland\", el grupo de protagonistas tendrá que viajar desde la Casa Blanca hasta el corazón de los Estados Unidos, sobreviviendo a nuevas clases de muertos vivientes que han evolucionado desde lo sucedido hace algunos años, así como a algunos supervivientes humanos rezagados. Pero, por encima de todo, tendrán que tratar de soportar los inconvenientes de convivir entre ellos.', '6.9', '2019-10-09 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/mIUGQ89isLNj4IRujDsXrZFIZCQ.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(38, 'Thor: Ragnarok', 'Thor está preso al otro lado del universo sin su poderoso martillo y se enfrenta a una carrera contra el tiempo. Su objetivo es volver a Asgard y parar el Ragnarok porque significaría la destrucción de su planeta natal y el fin de la civilización Asgardiana a manos de una todopoderosa y nueva amenaza, la implacable Hela. Pero, primero deberá sobrevivir a una competición letal de gladiadores que lo enfrentará a su aliado y compañero en los Vengadores, ¡el Increíble Hulk!', '7.5', '2017-10-25 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/sgVe7blGP5P71STv2TBXmO86qPo.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(39, 'Richard Jewell', 'Richard Jewell era un guardia de seguridad en los Juegos Olímpicos de Atlanta 1996, el cual descubrió una mochila con explosivos en su interior y evitó un número mayor de víctimas al ayudar a evacuar el área poco antes de que se produjera el estallido. En un principio se le presentó como un héroe cuya intervención salvó vidas, pero posteriormente Jewell pasó a ser considerado el sospechoso número uno y fue investigado como presunto culpable.', '7.5', '2019-12-13 00:00:00', 'en', 'https://image.tmdb.org/t/p/w500/yjg66Z7STW2TUaFJ3l555xPrzwF.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35'),
(40, 'デジモンアドベンチャー LAST EVOLUTION 絆', '', '10.0', '2020-02-21 00:00:00', 'ja', 'https://image.tmdb.org/t/p/w500/zw7MDRD7aek526rKLM04hAROGKy.jpg', '2020-03-11 19:53:35', '2020-03-11 19:53:35');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `movies`
--
ALTER TABLE `movies`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `movies`
--
ALTER TABLE `movies`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
